[project]
name = "agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "langchain>=1.2.7",
    "langchain-ollama>=1.0.1",
    "matplotlib>=3.10.8",
    "numpy>=2.2.6",
    "osmnx>=2.0.7",
    "rich>=14.2.0",
]
